MKdev::MqttForUnity::MqttConnector
string MKdev.MqttForUnity.MqttConnector.BrokerIp
string MKdev.MqttForUnity.MqttConnector.username
string MKdev.MqttForUnity.MqttConnector.password
MqttClient MKdev.MqttForUnity.MqttConnector.client
Dictionary<string, List<IMqttTopicReceiver> > MKdev.MqttForUnity.MqttConnector.DictTopicReceiver
Queue<MqttMsgPublishEventArgs> MKdev.MqttForUnity.MqttConnector.eventQueue
void MKdev.MqttForUnity.MqttConnector.Start()
void MKdev.MqttForUnity.MqttConnector.client_MqttMsgPublishReceived(object sender, MqttMsgPublishEventArgs e)
IEnumerator MKdev.MqttForUnity.MqttConnector.workQueueAndCall()
References MKdev.MqttForUnity.IMqttTopicReceiver.OnReceivedMessage.
void MKdev.MqttForUnity.MqttConnector.PublishMessage(string topic, string Message, EnumMqttQualityOfService MqttQOS_Level=EnumMqttQualityOfService.QOS_LEVEL_EXACTLY_ONCE)
Referenced by OnGuiMqttBsp.OnGUI.
void MKdev.MqttForUnity.MqttConnector.AddTopicReceiver(string topic, IMqttTopicReceiver receiver, EnumMqttQualityOfService MqttQOS_Level=EnumMqttQualityOfService.QOS_LEVEL_EXACTLY_ONCE)
Referenced by MKdev.MqttForUnity.MqttTopicDoAction.SetupLate, MKdev.MqttForUnity.MqttTopicToConsole.SetupLate.
void MKdev.MqttForUnity.MqttConnector.AddTopicReceiver(string topic, IMqttTopicReceiver receiver, byte MqttQOS_Level)