MKdev::ServerConfig::AbsServerConfig
abstract string MKdev.ServerConfig.AbsServerConfig.GetServerIp()
Referenced by MKdev.MqttForUnity.MqttConnector.Start.
abstract string MKdev.ServerConfig.AbsServerConfig.GetPassword()
Referenced by MKdev.MqttForUnity.MqttConnector.Start.
abstract string MKdev.ServerConfig.AbsServerConfig.GetUsername()
Referenced by MKdev.MqttForUnity.MqttConnector.Start.