MKdev::MqttForUnity::MqttConnector
AbsServerConfig MKdev.MqttForUnity.MqttConnector.ServerConfig
MqttClient MKdev.MqttForUnity.MqttConnector.client
Dictionary<string, List<IMqttTopicReceiver> > MKdev.MqttForUnity.MqttConnector.DictTopicReceiver
Queue<MqttMsgPublishEventArgs> MKdev.MqttForUnity.MqttConnector.receiverQueue
Queue<MqttMsgPublishEventArgs> MKdev.MqttForUnity.MqttConnector.senderQueue
void MKdev.MqttForUnity.MqttConnector.Start()
References MKdev.ServerConfig.AbsServerConfig.GetServerIp, MKdev.ServerConfig.AbsServerConfig.GetUsername, MKdev.ServerConfig.AbsServerConfig.GetPassword.
void MKdev.MqttForUnity.MqttConnector.client_MqttMsgPublishReceived(object sender, MqttMsgPublishEventArgs e)
The Methode client_MqttMsgPublishReceived is called, if a MqttMessage arrieved and put it into the receiverQueue client_MqttMsgPublishReceived seperats the thread which puts the message in the queue from working the message
void MKdev.MqttForUnity.MqttConnector.InitAndStartInnerCoroutines()
Inits and starts all InnerCoroutines
void MKdev.MqttForUnity.MqttConnector.StartInnerCoroutines()
Starts all InnerCoroutines
void MKdev.MqttForUnity.MqttConnector.StopInnerCoroutines()
Stops all InnerCoroutines
IEnumerator MKdev.MqttForUnity.MqttConnector.workReceiverQueueAndCall()
workReveiverQueueAndCall is a Inner Coroutine, which loops over the ReceivingQueue to call the Subscriper in this App workSenderQueueAndSend seperats the thread which puts the message in the queue from working the message
References MKdev.MqttForUnity.IMqttTopicReceiver.OnReceivedMessage.
IEnumerator MKdev.MqttForUnity.MqttConnector.workSenderQueueAndSend()
workSenderQueueAndSend is a Inner Coroutine, which loops over the senderQueue to send a Message if there is one workSenderQueueAndSend seperats the call to send from the sending its self
void MKdev.MqttForUnity.MqttConnector.PublishMessage(string topic, string Message, EnumMqttQualityOfService MqttQOS_Level=EnumMqttQualityOfService.QOS_LEVEL_EXACTLY_ONCE, bool retain=false)
PublishMessage enqueues the Message of a Topic in the Queue and the message will automaticaly, concurrently sended
Referenced by MKdev.MqttForUnity.MqttExample.OnGuiMqttBsp.OnGUI.
void MKdev.MqttForUnity.MqttConnector.AddTopicReceiver(string topic, IMqttTopicReceiver receiver, EnumMqttQualityOfService MqttQOS_Level=EnumMqttQualityOfService.QOS_LEVEL_EXACTLY_ONCE)
AddTopicReceiver added a receiver of an topic to the system. The receiver will autmaticaly called, if the topic gets a new message
Referenced by MKdev.MqttForUnity.MqttTopicDoAction.SetupLate, MKdev.MqttForUnity.MqttTopicToConsole.SetupLate, MKdev.MqttForUnity.MqttBricks.AbsDoActionByMqttTopicValue.SetupLate.
void MKdev.MqttForUnity.MqttConnector.AddTopicReceiver(string topic, IMqttTopicReceiver receiver, byte MqttQOS_Level)
AddTopicReceiver added a receiver of an topic to the system. The receiver will autmaticaly called, if the topic gets a new message