.TH "CreateObject" 3 "Tue Apr 23 2019" "MKdev.M2Mqtt" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CreateObject
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBCreateIt\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GameObject \fBobjectToCreate\fP"
.br
.ti -1c
.RI "Transform \fBtransformPosition\fP"
.br
.ti -1c
.RI "GameObject \fBnewGameObject\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void CreateObject\&.CreateIt ()"

.SH "Member Data Documentation"
.PP 
.SS "GameObject CreateObject\&.newGameObject"

.SS "GameObject CreateObject\&.objectToCreate"

.SS "Transform CreateObject\&.transformPosition"


.SH "Author"
.PP 
Generated automatically by Doxygen for MKdev\&.M2Mqtt from the source code\&.
