.TH "D:/workspace/Master-Pulls/MKdev.M2Mqtt.Unity3D/Assets/MKdev/MqttForUnity/Code/Logic/EnumCompareOperator.cs" 3 "Thu May 9 2019" "MKdev.M2Mqtt" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/workspace/Master-Pulls/MKdev.M2Mqtt.Unity3D/Assets/MKdev/MqttForUnity/Code/Logic/EnumCompareOperator.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBMKdev\&.Logic\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBMKdev\&.Logic\&.EnumCompareOperator\fP { \fBMKdev\&.Logic\&.EnumCompareOperator\&.equal\fP, \fBMKdev\&.Logic\&.EnumCompareOperator\&.smaller\fP, \fBMKdev\&.Logic\&.EnumCompareOperator\&.bigger\fP, \fBMKdev\&.Logic\&.EnumCompareOperator\&.smallerOr\fP, \fBMKdev\&.Logic\&.EnumCompareOperator\&.biggerOr\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MKdev\&.M2Mqtt from the source code\&.
