.TH "MKdev.MqttExample.OnGuiMqttBsp" 3 "Tue Apr 23 2019" "MKdev.M2Mqtt" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MKdev.MqttExample.OnGuiMqttBsp
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBMqttConnector\fP \fBMqttCon\fP"
.br
.ti -1c
.RI "string \fBpublishTopic\fP = 'hello/world'"
.br
.ti -1c
.RI "string \fBpublishString\fP = 'Sending from Unity3D!!!'"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnGUI\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void MKdev\&.MqttExample\&.OnGuiMqttBsp\&.OnGUI ()\fC [private]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBMqttConnector\fP MKdev\&.MqttExample\&.OnGuiMqttBsp\&.MqttCon"

.SS "string MKdev\&.MqttExample\&.OnGuiMqttBsp\&.publishString = 'Sending from Unity3D!!!'"

.SS "string MKdev\&.MqttExample\&.OnGuiMqttBsp\&.publishTopic = 'hello/world'"


.SH "Author"
.PP 
Generated automatically by Doxygen for MKdev\&.M2Mqtt from the source code\&.
