.TH "MKdev.MqttForUnity.MqttExample.CreateObject" 3 "Wed May 8 2019" "MKdev.M2Mqtt" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MKdev.MqttForUnity.MqttExample.CreateObject
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBCreateIt\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GameObject \fBobjectToCreate\fP"
.br
.ti -1c
.RI "Transform \fBtransformPosition\fP"
.br
.ti -1c
.RI "GameObject \fBnewGameObject\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void MKdev\&.MqttForUnity\&.MqttExample\&.CreateObject\&.CreateIt ()"

.SH "Member Data Documentation"
.PP 
.SS "GameObject MKdev\&.MqttForUnity\&.MqttExample\&.CreateObject\&.newGameObject"

.SS "GameObject MKdev\&.MqttForUnity\&.MqttExample\&.CreateObject\&.objectToCreate"

.SS "Transform MKdev\&.MqttForUnity\&.MqttExample\&.CreateObject\&.transformPosition"


.SH "Author"
.PP 
Generated automatically by Doxygen for MKdev\&.M2Mqtt from the source code\&.
