.TH "MKdev.ServerConfig.ConfigDetail" 3 "Thu May 9 2019" "MKdev.M2Mqtt" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MKdev.ServerConfig.ConfigDetail
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConfigDetail\fP ()"
.br
.ti -1c
.RI "\fBConfigDetail\fP (string serverIp, string username, string password)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBServerIp\fP"
.br
.ti -1c
.RI "string \fBUsername\fP"
.br
.ti -1c
.RI "string \fBPassword\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MKdev\&.ServerConfig\&.ConfigDetail\&.ConfigDetail ()"

.SS "MKdev\&.ServerConfig\&.ConfigDetail\&.ConfigDetail (string serverIp, string username, string password)"

.SH "Member Data Documentation"
.PP 
.SS "string MKdev\&.ServerConfig\&.ConfigDetail\&.Password"

.SS "string MKdev\&.ServerConfig\&.ConfigDetail\&.ServerIp"

.SS "string MKdev\&.ServerConfig\&.ConfigDetail\&.Username"


.SH "Author"
.PP 
Generated automatically by Doxygen for MKdev\&.M2Mqtt from the source code\&.
