.TH "MKdev.MqttForUnity" 3 "Wed May 8 2019" "MKdev.M2Mqtt" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MKdev.MqttForUnity
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBMqttBricks\fP"
.br
.ti -1c
.RI "namespace \fBMqttExample\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBIMqttTopicReceiver\fP"
.br
.ti -1c
.RI "class \fBMqttConnector\fP"
.br
.ti -1c
.RI "class \fBMqttTopicDoAction\fP"
.br
.ti -1c
.RI "class \fBMqttTopicToConsole\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBEnumMqttQualityOfService\fP : byte { \fBEnumMqttQualityOfService\&.QOS_LEVEL_AT_MOST_ONCE\fP =0x00, \fBEnumMqttQualityOfService\&.QOS_LEVEL_AT_LEAST_ONCE\fP = 0x01, \fBEnumMqttQualityOfService\&.QOS_LEVEL_EXACTLY_ONCE\fP = 0x02 }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBMKdev\&.MqttForUnity\&.EnumMqttQualityOfService\fP : byte\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIQOS_LEVEL_AT_MOST_ONCE \fP\fP
.TP
\fB\fIQOS_LEVEL_AT_LEAST_ONCE \fP\fP
.TP
\fB\fIQOS_LEVEL_EXACTLY_ONCE \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for MKdev\&.M2Mqtt from the source code\&.
