.TH "MKdev.MqttForUnity.IMqttTopicReceiver" 3 "Wed May 8 2019" "MKdev.M2Mqtt" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MKdev.MqttForUnity.IMqttTopicReceiver
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBMKdev\&.MqttForUnity\&.MqttBricks\&.AbsDoActionByMqttTopicValue\fP, \fBMKdev\&.MqttForUnity\&.MqttTopicDoAction\fP, and \fBMKdev\&.MqttForUnity\&.MqttTopicToConsole\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnReceivedMessage\fP (string topic, byte[] message)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void MKdev\&.MqttForUnity\&.IMqttTopicReceiver\&.OnReceivedMessage (string topic, byte [] message)"

.PP
Implemented in \fBMKdev\&.MqttForUnity\&.MqttBricks\&.AbsDoActionByMqttTopicValue\fP, \fBMKdev\&.MqttForUnity\&.MqttTopicDoAction\fP, and \fBMKdev\&.MqttForUnity\&.MqttTopicToConsole\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MKdev\&.M2Mqtt from the source code\&.
