.TH "MKdev.ServerConfig.ConfigObject" 3 "Wed May 8 2019" "MKdev.M2Mqtt" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MKdev.ServerConfig.ConfigObject
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMKdev\&.ServerConfig\&.AbsServerConfig\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override string \fBGetServerIp\fP ()"
.br
.ti -1c
.RI "override string \fBGetUsername\fP ()"
.br
.ti -1c
.RI "override string \fBGetPassword\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBServerIp\fP = '192\&.168\&.178\&.2'"
.br
.ti -1c
.RI "string \fBUsername\fP = 'uname'"
.br
.ti -1c
.RI "string \fBPassword\fP = 'securePwd'"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "override string MKdev\&.ServerConfig\&.ConfigObject\&.GetPassword ()\fC [virtual]\fP"

.PP
Implements \fBMKdev\&.ServerConfig\&.AbsServerConfig\fP\&.
.SS "override string MKdev\&.ServerConfig\&.ConfigObject\&.GetServerIp ()\fC [virtual]\fP"

.PP
Implements \fBMKdev\&.ServerConfig\&.AbsServerConfig\fP\&.
.SS "override string MKdev\&.ServerConfig\&.ConfigObject\&.GetUsername ()\fC [virtual]\fP"

.PP
Implements \fBMKdev\&.ServerConfig\&.AbsServerConfig\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string MKdev\&.ServerConfig\&.ConfigObject\&.Password = 'securePwd'"

.SS "string MKdev\&.ServerConfig\&.ConfigObject\&.ServerIp = '192\&.168\&.178\&.2'"

.SS "string MKdev\&.ServerConfig\&.ConfigObject\&.Username = 'uname'"


.SH "Author"
.PP 
Generated automatically by Doxygen for MKdev\&.M2Mqtt from the source code\&.
