.TH "MKdev.ServerConfig.ConfigFromFile" 3 "Wed Apr 24 2019" "MKdev.M2Mqtt" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MKdev.ServerConfig.ConfigFromFile
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMKdev\&.ServerConfig\&.AbsServerConfig\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override string \fBGetServerIp\fP ()"
.br
.ti -1c
.RI "override string \fBGetPassword\fP ()"
.br
.ti -1c
.RI "override string \fBGetUsername\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "override string MKdev\&.ServerConfig\&.ConfigFromFile\&.GetPassword ()\fC [virtual]\fP"

.PP
Implements \fBMKdev\&.ServerConfig\&.AbsServerConfig\fP\&.
.SS "override string MKdev\&.ServerConfig\&.ConfigFromFile\&.GetServerIp ()\fC [virtual]\fP"

.PP
Implements \fBMKdev\&.ServerConfig\&.AbsServerConfig\fP\&.
.SS "override string MKdev\&.ServerConfig\&.ConfigFromFile\&.GetUsername ()\fC [virtual]\fP"

.PP
Implements \fBMKdev\&.ServerConfig\&.AbsServerConfig\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MKdev\&.M2Mqtt from the source code\&.
