.TH "MKdev.Logic" 3 "Thu May 9 2019" "MKdev.M2Mqtt" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MKdev.Logic
.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBEnumCompareOperator\fP { \fBEnumCompareOperator\&.equal\fP, \fBEnumCompareOperator\&.smaller\fP, \fBEnumCompareOperator\&.bigger\fP, \fBEnumCompareOperator\&.smallerOr\fP, \fBEnumCompareOperator\&.biggerOr\fP }"
.br
.ti -1c
.RI "enum \fBEnumStringCompareOperator\fP { \fBEnumStringCompareOperator\&.equal\fP, \fBEnumStringCompareOperator\&.equalIgnoreCase\fP, \fBEnumStringCompareOperator\&.notEqual\fP, \fBEnumStringCompareOperator\&.notEqualIgnoreCase\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBMKdev\&.Logic\&.EnumCompareOperator\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIequal \fP\fP
.TP
\fB\fIsmaller \fP\fP
.TP
\fB\fIbigger \fP\fP
.TP
\fB\fIsmallerOr \fP\fP
.TP
\fB\fIbiggerOr \fP\fP
.SS "enum \fBMKdev\&.Logic\&.EnumStringCompareOperator\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIequal \fP\fP
.TP
\fB\fIequalIgnoreCase \fP\fP
.TP
\fB\fInotEqual \fP\fP
.TP
\fB\fInotEqualIgnoreCase \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for MKdev\&.M2Mqtt from the source code\&.
