.TH "MKdev.MqttForUnity.MqttConnectorSingleTon" 3 "Tue Apr 23 2019" "MKdev.M2Mqtt" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MKdev.MqttForUnity.MqttConnectorSingleTon
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMKdev\&.MqttForUnity\&.MqttConnector\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBMqttConnectorSingleTon\fP \fBGetInstance\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnApplicationQuit\fP ()"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static \fBMqttConnectorSingleTon\fP \fBs_Instance\fP = null"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "static \fBMqttConnectorSingleTon\fP MKdev\&.MqttForUnity\&.MqttConnectorSingleTon\&.GetInstance ()\fC [static]\fP"

.SS "void MKdev\&.MqttForUnity\&.MqttConnectorSingleTon\&.OnApplicationQuit ()\fC [private]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBMqttConnectorSingleTon\fP MKdev\&.MqttForUnity\&.MqttConnectorSingleTon\&.s_Instance = null\fC [static]\fP, \fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for MKdev\&.M2Mqtt from the source code\&.
