.TH "MKdev.ServerConfig.ConfigEditor.ConfigFromFileEditor" 3 "Wed May 8 2019" "MKdev.M2Mqtt" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MKdev.ServerConfig.ConfigEditor.ConfigFromFileEditor
.SH SYNOPSIS
.br
.PP
.PP
Inherits Editor\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnInspectorGUI\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "override void MKdev\&.ServerConfig\&.ConfigEditor\&.ConfigFromFileEditor\&.OnInspectorGUI ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for MKdev\&.M2Mqtt from the source code\&.
