.TH "MKdev.ServerConfig.AbsServerConfig" 3 "Wed May 8 2019" "MKdev.M2Mqtt" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MKdev.ServerConfig.AbsServerConfig
.SH SYNOPSIS
.br
.PP
.PP
Inherits ScriptableObject\&.
.PP
Inherited by \fBMKdev\&.ServerConfig\&.ConfigFromJSONFile\fP, and \fBMKdev\&.ServerConfig\&.ConfigObject\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "abstract string \fBGetServerIp\fP ()"
.br
.ti -1c
.RI "abstract string \fBGetPassword\fP ()"
.br
.ti -1c
.RI "abstract string \fBGetUsername\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "abstract string MKdev\&.ServerConfig\&.AbsServerConfig\&.GetPassword ()\fC [pure virtual]\fP"

.PP
Implemented in \fBMKdev\&.ServerConfig\&.ConfigFromJSONFile\fP, and \fBMKdev\&.ServerConfig\&.ConfigObject\fP\&.
.SS "abstract string MKdev\&.ServerConfig\&.AbsServerConfig\&.GetServerIp ()\fC [pure virtual]\fP"

.PP
Implemented in \fBMKdev\&.ServerConfig\&.ConfigFromJSONFile\fP, and \fBMKdev\&.ServerConfig\&.ConfigObject\fP\&.
.SS "abstract string MKdev\&.ServerConfig\&.AbsServerConfig\&.GetUsername ()\fC [pure virtual]\fP"

.PP
Implemented in \fBMKdev\&.ServerConfig\&.ConfigFromJSONFile\fP, and \fBMKdev\&.ServerConfig\&.ConfigObject\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MKdev\&.M2Mqtt from the source code\&.
