.TH "MKdev.MqttForUnity.MqttBricks.DoActionByMqttTopicArives" 3 "Wed May 8 2019" "MKdev.M2Mqtt" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MKdev.MqttForUnity.MqttBricks.DoActionByMqttTopicArives
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMKdev\&.MqttForUnity\&.MqttBricks\&.AbsDoActionByMqttTopicValue\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override bool \fBcompareOk\fP (byte[] message)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
It is a Brick, which does a Action if the configert Topic changes a value 
.SH "Member Function Documentation"
.PP 
.SS "override bool MKdev\&.MqttForUnity\&.MqttBricks\&.DoActionByMqttTopicArives\&.compareOk (byte [] message)\fC [virtual]\fP"

.PP
Implements \fBMKdev\&.MqttForUnity\&.MqttBricks\&.AbsDoActionByMqttTopicValue\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for MKdev\&.M2Mqtt from the source code\&.
