.TH "MKdev.MqttForUnity.DoActionByMqttTopicStringValue" 3 "Tue Apr 23 2019" "MKdev.M2Mqtt" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MKdev.MqttForUnity.DoActionByMqttTopicStringValue
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMKdev\&.MqttForUnity\&.DoActionByMqttTopicValue\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override bool \fBcompareOk\fP (byte[] message)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBEnumStringCompareOperator\fP \fBCompare\fP"
.br
.ti -1c
.RI "string \fBStrValue\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "override bool MKdev\&.MqttForUnity\&.DoActionByMqttTopicStringValue\&.compareOk (byte [] message)\fC [virtual]\fP"

.PP
Implements \fBMKdev\&.MqttForUnity\&.DoActionByMqttTopicValue\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBEnumStringCompareOperator\fP MKdev\&.MqttForUnity\&.DoActionByMqttTopicStringValue\&.Compare"

.SS "string MKdev\&.MqttForUnity\&.DoActionByMqttTopicStringValue\&.StrValue"


.SH "Author"
.PP 
Generated automatically by Doxygen for MKdev\&.M2Mqtt from the source code\&.
