.TH "MKdev.MqttForUnity.MqttBricks.DoActionByMqttTopicFloatValue" 3 "Wed May 8 2019" "MKdev.M2Mqtt" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MKdev.MqttForUnity.MqttBricks.DoActionByMqttTopicFloatValue
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMKdev\&.MqttForUnity\&.MqttBricks\&.AbsDoActionByMqttTopicValue\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override bool \fBcompareOk\fP (byte[] message)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBEnumCompareOperator\fP \fBCompare\fP"
.br
.ti -1c
.RI "float \fBIntValue\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "override bool MKdev\&.MqttForUnity\&.MqttBricks\&.DoActionByMqttTopicFloatValue\&.compareOk (byte [] message)\fC [virtual]\fP"

.PP
Implements \fBMKdev\&.MqttForUnity\&.MqttBricks\&.AbsDoActionByMqttTopicValue\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBEnumCompareOperator\fP MKdev\&.MqttForUnity\&.MqttBricks\&.DoActionByMqttTopicFloatValue\&.Compare"

.SS "float MKdev\&.MqttForUnity\&.MqttBricks\&.DoActionByMqttTopicFloatValue\&.IntValue"


.SH "Author"
.PP 
Generated automatically by Doxygen for MKdev\&.M2Mqtt from the source code\&.
